log:
  level: info

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: postgres://keto:keto@postgres:5432/keto?sslmode=disable

config:
  namespaces:
    location: file:///etc/config/keto/namespaces.yaml

