version: v0.13.0

dsn:
  {
    {
      printf "postgres://kratos:kratos@%s-postgres:5432/kratos?sslmode=disable&max_conns=20" (include "portal.fullname" .) | quote,
    },
  }

log:
  level: info
  format: json

serve:
  public:
    base_url: { { printf "%s/.ory/" (include "portal.publicURL" .) | quote } }
    cors:
      enabled: true
      allowed_origins:
        - { { include "portal.publicURL" . | quote } }
      allowed_methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed_headers:
        - Authorization
        - Content-Type
        - X-Requested-With
        - Accept
      exposed_headers:
        - Content-Type
      allow_credentials: true
  admin:
    base_url: { { printf "%s/" (include "portal.kratosAdminURL" .) | quote } }

secrets:
  cookie:
    - please-change-this-cookie-secret
  cipher:
    - 3HCf98UbOFiF7dR79Spl6HpwQYfLO1LF

identity:
  default_schema_id: portal
  schemas:
    - id: portal
      url: file:///etc/config/kratos/identity.schema.json

selfservice:
  default_browser_return_url: { { include "portal.publicURL" . | quote } }
  allowed_return_urls:
    - { { include "portal.publicURL" . | quote } }
    - { { printf "%s/*" (include "portal.publicURL" .) | quote } }
  flows:
    login:
      ui_url:
        { { printf "%s/auth/login" (include "portal.publicURL" .) | quote } }
      lifespan: 10m
    registration:
      ui_url:
        { { printf "%s/auth/register" (include "portal.publicURL" .) | quote } }
      lifespan: 10m
      after:
        code:
          hooks:
            - hook: session
            - hook: web_hook
              config:
                url:
                  {
                    {
                      printf "%s/api/internal/hooks/kratos/registration" (include "portal.backendInternalURL" .) | quote,
                    },
                  }
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgaWRlbnRpdHk6IGN0eC5pZGVudGl0eSwKfQo=
                headers:
                  Content-Type: application/json
                  Authorization: Basic a3JhdG9zOmtyYXRvcy1ob29r
    settings:
      ui_url:
        {
          {
            printf "%s/account/settings" (include "portal.publicURL" .) | quote,
          },
        }
    verification:
      enabled: true
      use: code
      ui_url:
        { { printf "%s/auth/verify" (include "portal.publicURL" .) | quote } }
    recovery:
      enabled: true
      ui_url:
        { { printf "%s/auth/recover" (include "portal.publicURL" .) | quote } }
      use: code
  methods:
    password:
      enabled: true
    code:
      enabled: true
      config:
        lifespan: 5m
        usage: login_registration_recovery
    link:
      enabled: false

courier:
  sms:
    enabled: true
    from: "+8610000000000"
  template_override_path: /etc/config/kratos/courier/templates
  channels:
    - id: sms
      type: http
      request_config:
        url: http://sms-mock:8080/messages
        method: POST
        body: base64://ZnVuY3Rpb24oY3R4KSB7CgogIFRvOiBjdHgucmVjaXBpZW50LAogIEJvZHk6IGN0eC5ib2R5LAoKfQ==
        headers:
          Content-Type: application/json

session:
  cookie:
    same_site: Lax

  lifespan: 720h

feature_flags:
  use_continue_with_transitions: true

hashers:
  argon2:
    parallelism: 2
    memory: 128MB
    iterations: 2
    salt_length: 16
    key_length: 32
