version: v0.14.0

dsn: {{ printf "postgres://keto:keto@%s-postgres:5432/keto?sslmode=disable" (include "portal.fullname" .) | quote }}

log:
  level: info

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

namespaces:
  location: file:///etc/config/keto/opl.ts
