version: v0.14.0

dsn: postgres://keto:keto@postgres:5432/keto?sslmode=disable

log:
  level: info

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

namespaces:
  location: file:///etc/config/keto/opl.ts
